version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd ip-treatment-offerings-service
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/offer .
      - docker tag service/offer 137034369116.dkr.ecr.us-west-2.amazonaws.com/offer-registry:offer
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 137034369116.dkr.ecr.us-west-2.amazonaws.com/offer-registry:offer
      - printf '[{"name":"offer-container","imageUri":"%s"}]' 137034369116.dkr.ecr.us-west-2.amazonaws.com/offer-registry:offer>taskdefinition.json
artifacts:
   files:
   - ip-treatment-offerings-service/taskdefinition.json